default:
  image: node:16-bullseye-slim
  interruptible: true

# This folders are cached between builds
cache: &cache
  paths:
    - node_modules/
    - dist/

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"' # Run when requested manually
      when: always
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' # Run on merge request
      when: always
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_OPEN_MERGE_REQUESTS' # Avoid duplicated pipelines
      when: never
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH' # Run on branch push
      when: always
    - when: never # Otherwise -> Don't pipeline

stages:
  - build
  - test
  - deploy

compile:
  stage: build
  cache:
    <<: *cache
    policy: push
  script:
    - npm ci
    - npm run docs
    - npm run tsc

jest:
  stage: test
  cache:
    <<: *cache
    policy: pull
  services:
    - name: mongo
      alias: mongo-docker
  script:
    - cp $DOTENV_TEST test.env
    - npm run test
  artifacts:
    when: always
    paths:
      - logs/
      - junit.xml
    reports:
      junit:
        - junit.xml

lint:
  stage: test
  cache:
    <<: *cache
    policy: pull
  script:
    - npm run lint

deploy-to-server:
  stage: deploy
  image: instrumentisto/rsync-ssh:alpine
  cache:
    <<: *cache
    policy: pull
  environment:
    name: development
  script:
    - cp $DOTENV_DEV .env
    - cp $SERVER_KEY server_key
    - set -e
    - echo "Deploy $CI_COMMIT_REF_NAME. Triggered by $CI_PIPELINE_SOURCE"
    - chmod 400 server_key
    - echo " === Creating directory... === "
    - ssh -o StrictHostKeyChecking=no -i server_key $SERVER_USER@$SERVER_IP "mkdir $SERVER_LOCATION -p"
    - echo " === Starting secure copy... === "
    - rsync -e "ssh -o StrictHostKeyChecking=no -i server_key" -r .env node_modules dist package.json $SERVER_USER@$SERVER_IP:$SERVER_LOCATION
    - echo " === Restarting server... === "
    - ssh -o StrictHostKeyChecking=no -i server_key $SERVER_USER@$SERVER_IP "pm2 restart $CI_PROJECT_NAME || pm2 start $SERVER_LOCATION/dist/index.js -n $CI_PROJECT_NAME"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success
    - if: "$CI_OPEN_MERGE_REQUESTS"
      when: on_success
    - when: manual
      allow_failure: true
